# Generated by Django 4.2.14 on 2024-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_usertopicstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
