# Generated by Django 4.2.14 on 2024-08-03 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lesson_userlessonscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
