# Generated by Django 4.2.14 on 2024-08-12 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_correct_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
