# Generated by Django 4.2.14 on 2024-08-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lesson_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Eedium', 'Medium'), ('Hard', 'Hard')], max_length=10),
        ),
    ]
