# Generated by Django 4.2.14 on 2024-08-12 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_question_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='status',
        ),
        migrations.AlterField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='usertopicstatus',
            unique_together={('user', 'topic')},
        ),
    ]
