# Generated by Django 4.2.14 on 2024-08-03 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_lesson_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlessonscore',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
