# Generated by Django 4.2.14 on 2024-08-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_topic_quiz_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.topic'),
        ),
    ]
