# Generated by Django 4.2.14 on 2024-08-06 14:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_quiz_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='api.lesson'),
            preserve_default=False,
        ),
    ]
