# Generated by Django 4.2.14 on 2024-08-06 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_quiz_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
    ]
