# Generated by Django 4.2.14 on 2024-08-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_userproblemscore_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='content',
        ),
    ]
