# Generated by Django 4.2.14 on 2024-08-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_lesson_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='category',
            field=models.CharField(choices=[('Dynamic Programming', 'Dynamic Programming'), ('Greedy', 'Greedy'), ('Graph', 'Graph'), ('Math', 'Math'), ('String', 'String'), ('Tree', 'Tree'), ('Elementary', 'Elementary')], max_length=20),
        ),
    ]
